# This file specifies the metadata of this Hugo theme

name = "Hugo-plus"
author = "Daniel Hatch (h4tch)"
homepage = "http://h4tch.github.com/project/hugo-plus"
description = "Functional and customizable static website platform built on Bootstrap with support for addons."
source_repo = "http://www.github.com/h4tch/hugo-plus"
license = "MIT"
licenselink = "https://github.com/H4tch/hugo-plus/blob/master/LICENSE.md"

tags = ["blog","project","authors","series"]
features = ["blog","project","authors","series","streams","themes","layouts","components","plugins"]
min_version = 0.13

[author]
	name = "Daniel Hatch"
	homepage = "http://h4tch.github.com"


